import { SITE } from "./site";

export type Lang = "ar" | "en";

export type PhaseId = "ledge-valley" | "aden-parks" | "siyal";

export type Phase = {
  id: PhaseId;
  name: string;
  nameAlt: string;
  kind: string;
  tagline: string;
  intro: string;
  price: string;
  priceNote: string;
  stats: { label: string; value: string }[];
  highlights: string[];
  units: { name: string; detail: string; area: string }[];
  images: { src: string; alt: string }[];
  waText: string;
};

export type LvRow = { floor: string; type: string; bua: number; terrace: number; deck?: number };
export type LvBuilding = { id: string; name: string; collection: string; floors: string; image: string; rows: LvRow[] };

const sqm = (l: Lang) => (l === "ar" ? "م²" : "m²");

// ------------------------------------------------------------------
// Shared numeric data for Ledge Valley buildings
// ------------------------------------------------------------------
type RawRow = [floorKey: string, typeKey: string, bua: number, terrace: number, deck?: number];
const FLOOR: Record<string, { ar: string; en: string }> = {
  G: { ar: "أرضي", en: "Ground" },
  F1: { ar: "أول", en: "First" },
  F2: { ar: "ثاني", en: "Second" },
  LG: { ar: "أرضي سفلي", en: "Lower ground" },
  GF: { ar: "أرضي + أول", en: "Ground + first" },
};
const TYPE: Record<string, { ar: string; en: string }> = {
  "3L": { ar: "3 غرف — لاجون", en: "3 bed — lagoon" },
  "3LL": { ar: "3 غرف لوفت — لاجون", en: "3 bed loft — lagoon" },
  "2CG": { ar: "غرفتان — شاليه بحديقة", en: "2 bed chalet — garden" },
  "1PS": { ar: "بنتهاوس سويت غرفة", en: "1 bed penthouse suite" },
  "3P": { ar: "بنتهاوس 3 غرف", en: "3 bed penthouse" },
  "4L": { ar: "4 غرف — لاجون", en: "4 bed — lagoon" },
  "3DL": { ar: "دوبلكس 3 غرف — لاجون", en: "3 bed duplex — lagoon" },
  "3DG": { ar: "دوبلكس 3 غرف بحديقة", en: "3 bed duplex — garden" },
  "2G": { ar: "غرفتان بحديقة", en: "2 bed — garden" },
  "1G": { ar: "غرفة بحديقة", en: "1 bed — garden" },
  "2": { ar: "غرفتان", en: "2 bed" },
  "1": { ar: "غرفة", en: "1 bed" },
  "2P": { ar: "بنتهاوس غرفتان", en: "2 bed penthouse" },
  "1P": { ar: "بنتهاوس غرفة", en: "1 bed penthouse" },
};
const BUILDINGS: { id: string; name: string; collection: string; floors: { ar: string; en: string }; image: string; rows: RawRow[] }[] = [
  {
    id: "fc-a", name: "Floating Chalet A", collection: "Island Collection",
    floors: { ar: "أرضي + أول", en: "G+1" }, image: "/images/lv-chalet-a.webp",
    rows: [["G", "3L", 114, 32, 20], ["G", "3LL", 132, 21, 16], ["G", "3LL", 131, 6, 17], ["F1", "2CG", 103, 22, 14]],
  },
  {
    id: "fc-b", name: "Floating Chalet B", collection: "Island Collection",
    floors: { ar: "أرضي + 2", en: "G+2" }, image: "/images/lv-chalet-b.webp",
    rows: [["G", "3L", 114, 32, 20], ["G", "3LL", 136, 18, 16], ["G", "3LL", 132, 6, 16], ["F1", "2CG", 103, 9, 15], ["F2", "1PS", 61, 8, 0], ["F2", "3P", 117, 46, 13]],
  },
  {
    id: "fc-c", name: "Floating Chalet C", collection: "Valley Collection",
    floors: { ar: "أرضي سفلي + 2", en: "LG+2" }, image: "/images/lv-chalet-c.webp",
    rows: [["LG", "3L", 126, 43, 8], ["LG", "4L", 133, 41, 12], ["GF", "3DL", 130, 14, 12], ["GF", "3DL", 128, 35, 9]],
  },
  {
    id: "type-a", name: "Type A", collection: "Valley Collection",
    floors: { ar: "أرضي + 2", en: "G+2" }, image: "/images/lv-type-a.webp",
    rows: [["G", "3DG", 130, 25], ["G", "2G", 89, 0], ["G", "2G", 102, 0], ["F1", "2", 83, 16], ["F1", "2CG", 90, 25], ["F2", "2P", 99, 22], ["F2", "2P", 88, 29]],
  },
  {
    id: "type-b", name: "Type B", collection: "Valley Collection",
    floors: { ar: "أرضي + 2", en: "G+2" }, image: "/images/lv-type-b.webp",
    rows: [["G", "1G", 75, 0], ["G", "2G", 92, 0], ["G", "2G", 101, 0], ["F1", "1", 61, 9], ["F1", "2CG", 82, 19], ["F1", "2CG", 89, 17], ["F2", "1P", 77, 19], ["F2", "3P", 122, 31]],
  },
];
const lvBuildings = (l: Lang): LvBuilding[] =>
  BUILDINGS.map((b) => ({
    id: b.id, name: b.name, collection: b.collection, floors: b.floors[l], image: b.image,
    rows: b.rows.map(([f, t, bua, terrace, deck]) => ({ floor: FLOOR[f][l], type: TYPE[t][l], bua, terrace, deck })),
  }));

const MIX = [
  { key: { ar: "غرفة نوم", en: "1 bed" }, share: 15, avg: 67 },
  { key: { ar: "غرفتان", en: "2 bed" }, share: 46, avg: 93 },
  { key: { ar: "3 غرف", en: "3 bed" }, share: 17, avg: 118 },
  { key: { ar: "دوبلكس 3 غرف", en: "3 bed duplex" }, share: 21, avg: 132 },
  { key: { ar: "4 غرف", en: "4 bed" }, share: 2, avg: 133 },
];

// ------------------------------------------------------------------
// Arabic
// ------------------------------------------------------------------
const ar = {
  lang: "ar" as Lang,
  dir: "rtl" as "rtl" | "ltr",
  home: "/",
  thanks: "/thank-you",
  switchLabel: "English",
  switchHref: "/en",
  meta: {
    title: "مكادي هايتس الغردقة | شاليهات وفيلات أوراسكوم — ليدج فالي، عدن باركس، سيال",
    description: `مكادي هايتس من أوراسكوم للتنمية في الغردقة. شاليهات عائمة على لاجون تبدأ من ${SITE.chaletsFrom} مليون، وفيلات تبدأ من ${SITE.villasFrom} مليون. ثلاث مراحل متاحة الآن.`,
  },
  brandLine: "مكادي هايتس",
  brandSub: "بواسطة أوراسكوم للتنمية",
  nav: [
    { href: "#phases", label: "المراحل المتاحة" },
    { href: "#ledge-valley-units", label: "وحدات ليدج فالي" },
    { href: "#masterplan", label: "المخطط العام" },
    { href: "#amenities", label: "الخدمات" },
    { href: "#location", label: "الموقع" },
    { href: "#faq", label: "أسئلة شائعة" },
  ],
  callNow: "اتصل الآن",
  menuOpen: "فتح القائمة",
  menuClose: "إغلاق القائمة",
  hero: {
    eyebrow: "أوراسكوم للتنمية — خليج مكادي، الغردقة",
    title: "مكادي هايتس",
    script: "Across the heights",
    lead: "شاليهات تنزل من ديكها الخاص إلى لاجون قابل للسباحة، وفيلات على ارتفاع 78 متراً فوق البحر الأحمر.",
    chalets: "شاليهات تبدأ من",
    villas: "فيلات تبدأ من",
    million: "مليون ج.م",
    wa: "اسأل على واتساب",
    seePhases: "شاهد المراحل المتاحة",
    available: "متاح الآن:",
    imgAlt: "شاليهات ليدج فالي العائمة على لاجون مكادي هايتس",
    formTitle: "احصل على قائمة الأسعار",
    formSub: "نرسل لك الكتيّب والوحدات المتاحة في المراحل الثلاث على واتساب.",
  },
  facts: [
    { v: "4.75 مليون م²", l: "مساحة مدينة مكادي هايتس" },
    { v: "78 متراً", l: "فوق سطح البحر — أعلى نقطة في خليج مكادي" },
    { v: "20 دقيقة", l: "من مطار الغردقة الدولي" },
    { v: "3 مراحل", l: "متاحة للبيع الآن داخل المشروع" },
  ],
  factsLabel: "أرقام المشروع",
  phasesSection: {
    title: "ثلاث مراحل متاحة للبيع الآن",
    lead: "شاليهات على المياه في ليدج فالي وعدن باركس، وفيلات منخفضة الكثافة في سيال. كل مرحلة بشخصية مختلفة داخل نفس المدينة.",
    model: "النموذج",
    rooms: "الغرف",
    area: "المساحة",
    indicative: "سعر استرشادي",
    priceOf: "أسعار",
    callback: "اطلب مكالمة",
    unitsCaption: "نماذج الوحدات في",
  },
  phases: [
    {
      id: "ledge-valley",
      name: "ليدج فالي",
      nameAlt: "Ledge Valley",
      kind: "شاليهات عائمة وشقق",
      tagline: "شاليهات بديك خاص فوق لاجون قابل للسباحة",
      intro: "أحدث مراحل مكادي هايتس. وحدات منخفضة الكثافة يطل أغلبها مباشرة على لاجونات وحمامات سباحة، مع ديكات خشبية خاصة تمتد فوق المياه، وحدائق وممشى داخلي يربط المرحلة كلها.",
      price: `تبدأ من ${SITE.chaletsFrom} مليون ج.م`,
      priceNote: "شاليه غرفة نوم",
      stats: [
        { label: "إجمالي الوحدات", value: "274" },
        { label: "مساحة الأرض", value: "91,049 م²" },
        { label: "مساحات الوحدات", value: "61 – 136 م²" },
      ],
      highlights: [
        "ديك خاص على المياه لوحدات الدور الأرضي",
        "إطلالات لاجون أو فالي أو حمام سباحة",
        "من غرفة حتى 4 غرف، ودوبلكس وبنتهاوس",
        "شلالات، حمام أطفال، ديك مغمور، منطقة يوجا",
      ],
      units: [
        { name: "بنتهاوس سويت", detail: "غرفة نوم واحدة", area: "61 م²" },
        { name: "شاليه بحديقة", detail: "غرفتا نوم", area: "103 م²" },
        { name: "شاليه لاجون", detail: "3 غرف نوم", area: "114 م²" },
        { name: "لوفت لاجون", detail: "3 غرف نوم", area: "131 – 136 م²" },
        { name: "دوبلكس لاجون", detail: "3 غرف نوم", area: "128 – 130 م²" },
        { name: "شاليه لاجون", detail: "4 غرف نوم", area: "133 م²" },
      ],
      images: [
        { src: "/images/lv-chalet-b.webp", alt: "شاليه عائم من نوع B على اللاجون في ليدج فالي" },
        { src: "/images/lv-deck.webp", alt: "ديك خشبي مظلل يطل على لاجون ليدج فالي" },
        { src: "/images/lv-chalet-c.webp", alt: "شاليه عائم من نوع C بإطلالة مياه" },
      ],
      waText: "مرحباً، أريد أسعار ووحدات ليدج فالي (Ledge Valley) في مكادي هايتس",
    },
    {
      id: "aden-parks",
      name: "عدن باركس",
      nameAlt: "Aden Parks",
      kind: "شاليهات وشقق بحدائق",
      tagline: "خصوصية في الهواء الطلق حول لاجون مركزي",
      intro: "مرحلة هادئة مستوحاة من ملاعب الجولف. عدد محدود من الوحدات في كل مبنى، ووحدات الأرضي لها مداخل خاصة وأفنية، ووحدات الأول الجانبية لها حدائقها الخاصة.",
      price: "شاليهات من غرفتين",
      priceNote: "اطلب أحدث قائمة أسعار",
      stats: [
        { label: "إجمالي الوحدات", value: "205" },
        { label: "مساحة الأرض", value: "82,000 م²" },
        { label: "مساحات الوحدات", value: "80 – 134 م²" },
      ],
      highlights: [
        "لاجون مركزي وحمامات إنفينيتي",
        "مداخل خاصة وأفنية لوحدات الأرضي",
        "كاياك ومساحات سباحة واسترخاء",
        "مبانٍ من 3 أدوار بعدد وحدات قليل",
      ],
      units: [
        { name: "Nest — شقة", detail: "غرفتا نوم", area: "80 م²" },
        { name: "Lush — شاليه بحديقة", detail: "غرفتا نوم", area: "87 م²" },
        { name: "Veranda — بتراس", detail: "غرفتا نوم", area: "94 م²" },
        { name: "Bloom — بحديقة وفناء", detail: "غرفتا نوم", area: "95 – 101 م²" },
        { name: "Haven — دوبلكس بحديقة", detail: "3 غرف نوم", area: "134 م²" },
      ],
      images: [
        { src: "/images/ad-lagoon.webp", alt: "اللاجون المركزي في عدن باركس" },
        { src: "/images/ad-type-a.webp", alt: "مبنى Type A في عدن باركس بحديقة وحمام سباحة" },
        { src: "/images/ad-view.webp", alt: "إطلالة تراس على مياه عدن باركس" },
      ],
      waText: "مرحباً، أريد أسعار ووحدات عدن باركس (Aden Parks) في مكادي هايتس",
    },
    {
      id: "siyal",
      name: "سيال",
      nameAlt: "Siyal",
      kind: "فيلات مستقلة وتوين وتاون هاوس",
      tagline: "فيلات على مساحة مفتوحة، 12% فقط مبانٍ",
      intro: "حي فيلات منخفض الكثافة: 78 وحدة فقط على 82,500 م²، وأغلب الأرض مخصص للمساحات الخضراء والمياه. واجهات بألوان الصحراء الهادئة، ومداخل بارتفاع مزدوج في بعض النماذج.",
      price: `تبدأ من ${SITE.villasFrom} مليون ج.م`,
      priceNote: "تاون هاوس",
      stats: [
        { label: "إجمالي الوحدات", value: "78" },
        { label: "مساحة الأرض", value: "82,500 م²" },
        { label: "مساحات الفيلات", value: "136 – 250 م²" },
      ],
      highlights: [
        "حمام سباحة خاص في الـ Signature والـ Courtyard",
        "روف واسع في كل النماذج",
        "غرفة مربية بحمام في كل فيلا",
        "جيم مفتوح، جيم مائي، ومساحة يوجا",
      ],
      units: [
        { name: "تاون هاوس", detail: "3 غرف نوم", area: "136 – 138 م²" },
        { name: "توين فيلا", detail: "3 غرف نوم", area: "144 – 145 م²" },
        { name: "Boutique Villa", detail: "3 غرف نوم", area: "160 م²" },
        { name: "Deluxe Villa", detail: "4 غرف نوم", area: "175 م²" },
        { name: "Grand Villa", detail: "4 غرف نوم", area: "190 م²" },
        { name: "Courtyard Villa", detail: "4 غرف + فناء بحمام سباحة", area: "210 م²" },
        { name: "Signature Villa", detail: "5 غرف + حمام سباحة", area: "250 م²" },
      ],
      images: [
        { src: "/images/sy-deluxe.webp", alt: "Deluxe Villa في سيال بحمام سباحة" },
        { src: "/images/sy-pool.webp", alt: "حمام السباحة الرئيسي في سيال" },
        { src: "/images/sy-grand.webp", alt: "Grand Villa في سيال" },
      ],
      waText: "مرحباً، أريد أسعار فيلات سيال (Siyal) في مكادي هايتس",
    },
  ] as Phase[],
  lv: {
    eyebrow: "ليدج فالي — المرحلة الأولى",
    title: "كل نموذج ومساحاته بالتفصيل",
    lead: "خمسة نماذج مبانٍ في مجموعتين: Island Collection على الجزيرة الوسطى بين اللاجونين، و Valley Collection حولها. المساحات بالمتر المربع من كتيّب المبيعات وقابلة للتعديل.",
    mixTitle: "توزيع وحدات المرحلة الأولى (194 وحدة)",
    avg: "متوسط",
    tabs: "نماذج المباني",
    floor: "الدور",
    type: "نوع الوحدة",
    area: "المساحة",
    terrace: "تراس مكشوف",
    deck: "ديك",
    mirror: "يوجد نموذج معكوس (Mirror) لكل شاليه عائم بنفس المساحات. المساحات تقريبية.",
    available: "المتاح من",
    plans: "اطلب المساقط الكاملة",
    facade: "واجهة",
    waText: (b: string) => `مرحباً، أريد الوحدات المتاحة وأسعار ${b} في ليدج فالي - مكادي هايتس`,
    gallery: [
      { src: "/images/lv-pool.webp", t: "لاجونات وحمامات سباحة حولها أنشطة" },
      { src: "/images/lv-court.webp", t: "مستويات وإطلالات بين المباني" },
      { src: "/images/lv-park.webp", t: "حدائق وممشى داخلي" },
      { src: "/images/lv-roof.webp", t: "روف وتراسات للبنتهاوس" },
    ],
  },
  mp: {
    title: "مكان كل مرحلة داخل المدينة",
    lead: "المخطط العام من تصميم EDSA. سيال وعدن باركس في الجزء الشمالي الغربي قرب عدن وتاون ووك، وليدج فالي في الشرق بجوار ليدج فلير، وكلها على مسافة دقائق من الشاطئ ومنطقة وسط المدينة M Town.",
    alt: "المخطط العام لمكادي هايتس وموقع مراحل سيال وعدن باركس وليدج فالي",
    note: "المخطط للتوضيح فقط. اسحب أفقياً على الموبايل لرؤية الخريطة كاملة.",
  },
  amenities: {
    title: "مدينة متكاملة طوال السنة، مش مصيف",
    lead: "مكادي هايتس تجمع السكن والشقق الفندقية والفنادق والمنطقة التجارية في مكان واحد، فالحياة فيها مستمرة في الشتاء والصيف.",
    imgAlt: "ديك خاص لشاليه عائم يطل على المياه",
    items: [
      { title: "حياة ساحلية", text: "سباحة وكايت سيرف وكاياك وسنوركلينج، مع لاونجات شاطئية على البحر الأحمر." },
      { title: "ذا هاوس The Haus", text: "مسرح متعدد الاستخدامات يتسع لأكثر من 3,400 ضيف للحفلات والأفراح والمؤتمرات، بجانب فنادق بوتيك وفنادق كاملة." },
      { title: "نادٍ رياضي", text: "ملاعب كرة قدم وبادل وتنس، وجيم مجهز، ومساحات يوجا موزعة في المشروع." },
      { title: "خدمات طبية", text: "عيادات داخل المشروع للرعاية الأساسية والوصول السريع للدعم الصحي." },
      { title: "تعليم", text: "حضانة ومرحلة ما قبل المدرسة داخل المجتمع للعائلات الصغيرة." },
      { title: "تسوق ومطاعم", text: "كافيهات ومطاعم ومنطقة تجارية بممرات مظللة وبنوك وكل الاحتياجات اليومية." },
    ],
    lvTitle: "داخل ليدج فالي تحديداً",
    lvText: "لاجونان قابلان للسباحة، شلالان، حمام سباحة رئيسي وحمام أطفال، ديك مغمور وصن ديك، منطقتا ألعاب أطفال، مساحة يوجا، جلسات خارجية، ومطعم وكافيه.",
  },
  location: {
    title: "قلب خليج مكادي، جنوب الغردقة",
    lead: "على أعلى نقطة في خليج مكادي، بإطلالات مفتوحة على البحر الأحمر، وقريبة من سهل حشيش وسوما باي ومراسي ريد سي.",
    items: [
      { place: "مطار الغردقة الدولي", time: "20 دقيقة" },
      { place: "وسط الغردقة", time: "30 دقيقة" },
      { place: "الجونة", time: "45 دقيقة" },
    ],
    mapTitle: "موقع مكادي هايتس على الخريطة",
  },
  dev: {
    eyebrow: "المطوّر",
    title: "أوراسكوم للتنمية",
    lead: "المطوّر الذي بنى الجونة وحوّلها لمدينة تعيش طوال السنة. نفس الفكرة تتكرر في مكادي هايتس: مدينة متكاملة بخدماتها، لا قرية موسمية.",
    portfolio: ["الجونة", "طابا هايتس", "مكادي هايتس", "أو ويست", "أندرمات — سويسرا", "لستيكا باي — الجبل الأسود"],
    partnersTitle: "شركاء التصميم",
    partners: [
      { name: "EDSA", role: "المخطط العام لمكادي هايتس" },
      { name: "Die Stadt", role: "مخطط ليدج فالي" },
      { name: "Innovation Design Studio", role: "عمارة ليدج فالي" },
    ],
  },
  gallery: {
    title: "من الداخل والخارج",
    note: "الصور تصورات معمارية للتوضيح وقد تختلف عن الواقع.",
    alts: ["سلم خارجي لشاليه عائم على المياه", "معيشة بإطلالة على اللاجون", "Courtyard Villa في سيال", "تراس بأقواس وسور أخضر", "تشطيب داخلي في عدن باركس", "غرفة نوم تطل على المياه"],
  },
  faqTitle: "أسئلة شائعة",
  faq: [
    { q: "أين يقع مشروع مكادي هايتس؟", a: "في قلب خليج مكادي جنوب الغردقة على ساحل البحر الأحمر، على ارتفاع 78 متراً فوق سطح البحر، وعلى بعد نحو 20 دقيقة من مطار الغردقة الدولي." },
    { q: "ما المراحل المتاحة للبيع حالياً؟", a: "ثلاث مراحل: ليدج فالي (شاليهات عائمة وشقق)، عدن باركس (شاليهات وشقق بحدائق)، وسيال (فيلات مستقلة وتوين وتاون هاوس)." },
    { q: "كم يبدأ سعر الشاليه والفيلا؟", a: `الشاليهات تبدأ من ${SITE.chaletsFrom} مليون جنيه لوحدة غرفة نوم، والفيلات تبدأ من ${SITE.villasFrom} مليون جنيه للتاون هاوس. الأسعار استرشادية وتتغير حسب الوحدة والإطلالة والدور وقت الحجز.` },
    { q: "ما المقصود بالشاليه العائم في ليدج فالي؟", a: "وحدات الدور الأرضي مصممة على حافة لاجونات قابلة للسباحة، ولكل وحدة ديك خشبي خاص يمتد فوق المياه، فتنزل من الوحدة إلى المياه مباشرة." },
    { q: "من المطوّر؟", a: "أوراسكوم للتنمية، مطوّر الجونة وطابا هايتس ومكادي هايتس، بمخطط عام من EDSA، وتصميم ليدج فالي من Die Stadt و Innovation Design Studio." },
    { q: "هل يمكن حجز معاينة أو استلام الكتيّب الكامل؟", a: "نعم، اترك بياناتك أو راسلنا على واتساب وسنرسل لك الكتيّب وقائمة الوحدات المتاحة وننسق موعد المعاينة." },
  ],
  contact: {
    title: "احجز وحدتك قبل نفاد الإطلالات الأولى",
    lead: "وحدات الصف الأول على اللاجون عددها محدود في كل مرحلة. اترك رقمك ونرسل لك المتاح الآن بالأسعار والمساقط.",
    payment: "أنظمة سداد بالتقسيط على سنوات",
    paymentNote: "تواصل معنا لمعرفة خطة السداد المتاحة لكل مرحلة ووحدة.",
    formTitle: "اطلب الأسعار والكتيّب",
    formSub: "سنتواصل معك على الرقم الذي تكتبه.",
    wa: "واتساب",
  },
  form: {
    name: "الاسم",
    phone: "رقم الموبايل / واتساب",
    phase: "المرحلة المهتم بها",
    undecided: "لم أحدد بعد",
    submit: "أرسل لي الأسعار والكتيّب",
    sending: "جارٍ الإرسال…",
    errName: "اكتب اسمك من حرفين على الأقل.",
    errPhone: "اكتب رقم موبايل صحيح من 10 إلى 15 رقماً، مثل 01xxxxxxxxx أو ‎+9665xxxxxxxx.",
    errNet: "لم يتم إرسال الطلب بسبب مشكلة في الاتصال. حاول مرة أخرى أو راسلنا على واتساب.",
    consent: "بإرسال بياناتك توافق على أن نتواصل معك بخصوص المشروع وفق",
    privacy: "سياسة الخصوصية",
  },
  popup: { title: "قائمة أسعار مكادي هايتس", sub: "أسعار ووحدات ليدج فالي وعدن باركس وسيال المتاحة الآن، على واتساب.", close: "إغلاق" },
  mobileForm: { title: "احصل على قائمة الأسعار", sub: "الكتيّب والوحدات المتاحة في المراحل الثلاث على واتساب." },
  bar: { call: "اتصال", wa: "واتساب", prices: "الأسعار" },
  cookie: { text: "نستخدم ملفات تعريف الارتباط لقياس أداء الإعلانات وتحسين الصفحة.", details: "التفاصيل", ok: "موافق", close: "إغلاق" },
  footer: {
    title: "مكادي هايتس — الغردقة",
    sub: "ليدج فالي، عدن باركس، سيال",
    phone: "هاتف وواتساب:",
    email: "بريد:",
    disclosureLabel: "إفصاح:",
    disclosure: `هذه الصفحة يديرها ${SITE.brand}، مسوّق عقاري مستقل، وليست الموقع الرسمي لشركة أوراسكوم للتنمية. أسماء المشروعات والعلامات التجارية والصور مملوكة لأصحابها وتُستخدم لأغراض التعريف فقط.`,
    pricesLabel: "أسعار استرشادية:",
    prices: "جميع الأسعار والمساحات المعروضة استرشادية وقابلة للتغيير دون إشعار، والسعر النهائي يحدده المطوّر وقت الحجز حسب الوحدة والدور والإطلالة. الصور تصورات معمارية للتوضيح.",
    privacy: "سياسة الخصوصية وإخلاء المسؤولية",
  },
  privacy: {
    title: "سياسة الخصوصية وإخلاء المسؤولية",
    blocks: [
      { h: "", p: `هذه الصفحة يديرها ${SITE.brand}، مسوّق عقاري مستقل. الصفحة ليست الموقع الرسمي لشركة أوراسكوم للتنمية، وجميع العلامات التجارية وأسماء المشروعات مملوكة لأصحابها.` },
      { h: "البيانات التي نجمعها", p: "نجمع الاسم ورقم الهاتف والمرحلة التي تهتم بها عند إرسال النموذج، ونستخدمها فقط للتواصل معك بخصوص الوحدات والأسعار والمعاينات. لا نبيع بياناتك لأي طرف ثالث، وقد نشاركها مع المطوّر لغرض إتمام الحجز فقط بموافقتك." },
      { h: "ملفات تعريف الارتباط والإعلانات", p: "نستخدم ملفات تعريف الارتباط وأدوات Google Ads لقياس أداء الإعلانات وعدد الطلبات. يمكنك تعطيلها من إعدادات المتصفح." },
      { h: "الأسعار والمواصفات", p: "الأسعار المعروضة أسعار استرشادية وقد تتغير دون إشعار مسبق حسب الوحدة والدور والإطلالة وسياسة المطوّر وقت الحجز. الصور والمساقط للتوضيح فقط، والمساحات تقريبية وقابلة للتعديل وفق العقد النهائي." },
      { h: "حذف البيانات", p: `لطلب حذف بياناتك راسلنا على ${SITE.email} أو على رقم ${SITE.phone}.` },
    ],
    close: "إغلاق",
  },
  thankYou: {
    metaTitle: "تم استلام طلبك | مكادي هايتس",
    title: "تم استلام طلبك",
    text: "سنتواصل معك على رقمك بتفاصيل وأسعار مكادي هايتس. لو تحب تبدأ الآن، راسلنا مباشرة.",
    wa: "كمّل على واتساب",
    back: "العودة للصفحة الرئيسية",
  },
  waDefault: SITE.whatsappText,
  pins: { siyal: "سيال", "aden-parks": "عدن باركس", "ledge-valley": "ليدج فالي" } as Record<PhaseId, string>,
  sqm: sqm("ar"),
  lvBuildings: lvBuildings("ar"),
  mix: MIX.map((m) => ({ type: m.key.ar, share: m.share, avg: m.avg })),
};

export type Content = typeof ar;

// ------------------------------------------------------------------
// English
// ------------------------------------------------------------------
const en: Content = {
  lang: "en",
  dir: "ltr",
  home: "/en",
  thanks: "/en/thank-you",
  switchLabel: "العربية",
  switchHref: "/",
  meta: {
    title: "Makadi Heights Hurghada | Orascom Chalets & Villas — Ledge Valley, Aden Parks, Siyal",
    description: `Makadi Heights by Orascom Development, Hurghada. Floating lagoon chalets from EGP ${SITE.chaletsFrom}M and villas from EGP ${SITE.villasFrom}M. Three phases now selling.`,
  },
  brandLine: "Makadi Heights",
  brandSub: "by Orascom Development",
  nav: [
    { href: "#phases", label: "Phases" },
    { href: "#ledge-valley-units", label: "Ledge Valley units" },
    { href: "#masterplan", label: "Masterplan" },
    { href: "#amenities", label: "Amenities" },
    { href: "#location", label: "Location" },
    { href: "#faq", label: "FAQ" },
  ],
  callNow: "Call now",
  menuOpen: "Open menu",
  menuClose: "Close menu",
  hero: {
    eyebrow: "Orascom Development — Makadi Bay, Hurghada",
    title: "Makadi Heights",
    script: "Across the heights",
    lead: "Chalets that step from a private deck into a swimmable lagoon, and villas 78 metres above the Red Sea.",
    chalets: "Chalets from",
    villas: "Villas from",
    million: "M EGP",
    wa: "Ask on WhatsApp",
    seePhases: "View available phases",
    available: "Now selling:",
    imgAlt: "Ledge Valley floating chalets on the Makadi Heights lagoon",
    formTitle: "Get the price list",
    formSub: "We'll send the brochure and available units across all three phases on WhatsApp.",
  },
  facts: [
    { v: "4.75M m²", l: "Total area of Makadi Heights" },
    { v: "78 m", l: "Above sea level — the highest point of Makadi Bay" },
    { v: "20 min", l: "From Hurghada International Airport" },
    { v: "3 phases", l: "Now selling inside the town" },
  ],
  factsLabel: "Project facts",
  phasesSection: {
    title: "Three phases now selling",
    lead: "Waterfront chalets in Ledge Valley and Aden Parks, and low-density villas in Siyal. Each has its own character within the same town.",
    model: "Model",
    rooms: "Bedrooms",
    area: "Area",
    indicative: "indicative price",
    priceOf: "Prices for",
    callback: "Request a call",
    unitsCaption: "Unit models in",
  },
  phases: [
    {
      id: "ledge-valley",
      name: "Ledge Valley",
      nameAlt: "ليدج فالي",
      kind: "Floating chalets & apartments",
      tagline: "Chalets with a private deck over a swimmable lagoon",
      intro: "The newest phase of Makadi Heights. Low-density homes, most facing lagoons or pools directly, with private timber decks that extend over the water, gardens and an inner promenade linking the whole phase.",
      price: `From EGP ${SITE.chaletsFrom}M`,
      priceNote: "1-bedroom chalet",
      stats: [
        { label: "Total units", value: "274" },
        { label: "Land area", value: "91,049 m²" },
        { label: "Unit sizes", value: "61 – 136 m²" },
      ],
      highlights: [
        "Private water deck for ground-floor units",
        "Lagoon, valley or pool views",
        "1 to 4 bedrooms, duplexes and penthouses",
        "Waterfalls, kids' pool, submerged deck, yoga area",
      ],
      units: [
        { name: "Penthouse suite", detail: "1 bedroom", area: "61 m²" },
        { name: "Garden chalet", detail: "2 bedrooms", area: "103 m²" },
        { name: "Lagoon chalet", detail: "3 bedrooms", area: "114 m²" },
        { name: "Lagoon loft", detail: "3 bedrooms", area: "131 – 136 m²" },
        { name: "Lagoon duplex", detail: "3 bedrooms", area: "128 – 130 m²" },
        { name: "Lagoon chalet", detail: "4 bedrooms", area: "133 m²" },
      ],
      images: [
        { src: "/images/lv-chalet-b.webp", alt: "Floating Chalet B on the Ledge Valley lagoon" },
        { src: "/images/lv-deck.webp", alt: "Shaded timber deck overlooking the Ledge Valley lagoon" },
        { src: "/images/lv-chalet-c.webp", alt: "Floating Chalet C with water views" },
      ],
      waText: "Hello, I'd like prices and available units in Ledge Valley, Makadi Heights",
    },
    {
      id: "aden-parks",
      name: "Aden Parks",
      nameAlt: "عدن باركس",
      kind: "Chalets & garden apartments",
      tagline: "Open-air privacy around a central lagoon",
      intro: "A calm, golf-inspired neighbourhood. Few units per building; ground-floor homes have private entrances and courtyards, and first-floor side units have their own gardens.",
      price: "2-bedroom chalets",
      priceNote: "Ask for the latest price list",
      stats: [
        { label: "Total units", value: "205" },
        { label: "Land area", value: "82,000 m²" },
        { label: "Unit sizes", value: "80 – 134 m²" },
      ],
      highlights: [
        "Central lagoon and infinity pools",
        "Private entrances and courtyards on the ground floor",
        "Kayaking, swimming and lounge areas",
        "Three-storey buildings with few units each",
      ],
      units: [
        { name: "Nest — apartment", detail: "2 bedrooms", area: "80 m²" },
        { name: "Lush — garden chalet", detail: "2 bedrooms", area: "87 m²" },
        { name: "Veranda — terrace", detail: "2 bedrooms", area: "94 m²" },
        { name: "Bloom — garden & courtyard", detail: "2 bedrooms", area: "95 – 101 m²" },
        { name: "Haven — garden duplex", detail: "3 bedrooms", area: "134 m²" },
      ],
      images: [
        { src: "/images/ad-lagoon.webp", alt: "The central lagoon at Aden Parks" },
        { src: "/images/ad-type-a.webp", alt: "Aden Parks Type A building with garden and pool" },
        { src: "/images/ad-view.webp", alt: "Terrace view over the water at Aden Parks" },
      ],
      waText: "Hello, I'd like prices and available units in Aden Parks, Makadi Heights",
    },
    {
      id: "siyal",
      name: "Siyal",
      nameAlt: "سيال",
      kind: "Standalone, twin & townhouse villas",
      tagline: "Villas on open land — only 12% built",
      intro: "A low-density villa neighbourhood: just 78 homes on 82,500 m², with most of the land given to greenery and water. Soft desert-toned façades, and double-height entrances in selected models.",
      price: `From EGP ${SITE.villasFrom}M`,
      priceNote: "Townhouse",
      stats: [
        { label: "Total units", value: "78" },
        { label: "Land area", value: "82,500 m²" },
        { label: "Villa sizes", value: "136 – 250 m²" },
      ],
      highlights: [
        "Private pool in the Signature and Courtyard villas",
        "Generous roof in every model",
        "Nanny's room with bathroom in every villa",
        "Open-air gym, water gym and yoga space",
      ],
      units: [
        { name: "Townhouse", detail: "3 bedrooms", area: "136 – 138 m²" },
        { name: "Twin villa", detail: "3 bedrooms", area: "144 – 145 m²" },
        { name: "Boutique Villa", detail: "3 bedrooms", area: "160 m²" },
        { name: "Deluxe Villa", detail: "4 bedrooms", area: "175 m²" },
        { name: "Grand Villa", detail: "4 bedrooms", area: "190 m²" },
        { name: "Courtyard Villa", detail: "4 bed + pool courtyard", area: "210 m²" },
        { name: "Signature Villa", detail: "5 bed + private pool", area: "250 m²" },
      ],
      images: [
        { src: "/images/sy-deluxe.webp", alt: "Siyal Deluxe Villa with pool" },
        { src: "/images/sy-pool.webp", alt: "The main pool at Siyal" },
        { src: "/images/sy-grand.webp", alt: "Siyal Grand Villa" },
      ],
      waText: "Hello, I'd like prices for Siyal villas, Makadi Heights",
    },
  ],
  lv: {
    eyebrow: "Ledge Valley — Phase 1",
    title: "Every model, every area",
    lead: "Five building types in two collections: the Island Collection on the central island between the two lagoons, and the Valley Collection around it. Areas in m² from the sales kit, subject to change.",
    mixTitle: "Phase 1 unit mix (194 units)",
    avg: "avg.",
    tabs: "Building types",
    floor: "Floor",
    type: "Unit type",
    area: "Area",
    terrace: "Open terrace",
    deck: "Deck",
    mirror: "Each floating chalet also comes in a mirrored layout with the same areas. Areas are approximate.",
    available: "Available in",
    plans: "Request full floor plans",
    facade: "Façade of",
    waText: (b: string) => `Hello, I'd like available units and prices for ${b} in Ledge Valley, Makadi Heights`,
    gallery: [
      { src: "/images/lv-pool.webp", t: "Lagoons and pools with activities around them" },
      { src: "/images/lv-court.webp", t: "Levels and views between buildings" },
      { src: "/images/lv-park.webp", t: "Gardens and an inner promenade" },
      { src: "/images/lv-roof.webp", t: "Roofs and terraces for penthouses" },
    ],
  },
  mp: {
    title: "Where each phase sits",
    lead: "Masterplan by EDSA. Siyal and Aden Parks are in the north-west near Aden and Townwalk; Ledge Valley is in the east next to Ledge Flare — all minutes from the beach and the M Town downtown.",
    alt: "Makadi Heights masterplan showing Siyal, Aden Parks and Ledge Valley",
    note: "For illustration only. Swipe sideways on mobile to see the full map.",
  },
  amenities: {
    title: "A year-round town, not a summer resort",
    lead: "Makadi Heights combines homes, serviced apartments, hotels and a commercial district in one place, so life continues in winter as well as summer.",
    imgAlt: "Private deck of a floating chalet over the water",
    items: [
      { title: "Coastal living", text: "Swimming, kitesurfing, kayaking and snorkelling, with beach lounges on the Red Sea." },
      { title: "The Haus", text: "A multipurpose venue for over 3,400 guests — concerts, weddings and summits — alongside boutique and full-scale hotels." },
      { title: "Sports club", text: "Football, padel and tennis courts, a fully equipped gym and yoga spaces across the town." },
      { title: "Medical", text: "On-site clinics for everyday care and quick access to health support." },
      { title: "Education", text: "A preschool within the community for young families." },
      { title: "Retail & dining", text: "Cafés, restaurants and shaded retail courts with banks and daily essentials." },
    ],
    lvTitle: "Inside Ledge Valley",
    lvText: "Two swimmable lagoons, two waterfalls, a main pool and kids' pool, a submerged deck and sun deck, two kids' play areas, a yoga area, outdoor seating, and a café and restaurant.",
  },
  location: {
    title: "The heart of Makadi Bay, south of Hurghada",
    lead: "On the highest point of Makadi Bay with open Red Sea views, close to Sahl Hasheesh, Soma Bay and Marassi Red Sea.",
    items: [
      { place: "Hurghada International Airport", time: "20 min" },
      { place: "Downtown Hurghada", time: "30 min" },
      { place: "El Gouna", time: "45 min" },
    ],
    mapTitle: "Makadi Heights on the map",
  },
  dev: {
    eyebrow: "Developer",
    title: "Orascom Development",
    lead: "The developer that built El Gouna into a year-round town. Makadi Heights follows the same idea: a complete, fully serviced town rather than a seasonal village.",
    portfolio: ["El Gouna", "Taba Heights", "Makadi Heights", "O West", "Andermatt — Switzerland", "Luštica Bay — Montenegro"],
    partnersTitle: "Design partners",
    partners: [
      { name: "EDSA", role: "Makadi Heights masterplan" },
      { name: "Die Stadt", role: "Ledge Valley masterplan" },
      { name: "Innovation Design Studio", role: "Ledge Valley architecture" },
    ],
  },
  gallery: {
    title: "Inside and out",
    note: "Images are architectural renders for illustration and may differ from the final product.",
    alts: ["Exterior stair of a floating chalet on the water", "Living room with lagoon view", "Siyal Courtyard Villa", "Arched terrace with green railing", "Aden Parks interior finish", "Bedroom facing the water"],
  },
  faqTitle: "Frequently asked questions",
  faq: [
    { q: "Where is Makadi Heights?", a: "In the heart of Makadi Bay, south of Hurghada on the Red Sea, 78 metres above sea level and about 20 minutes from Hurghada International Airport." },
    { q: "Which phases are selling now?", a: "Three: Ledge Valley (floating chalets and apartments), Aden Parks (chalets and garden apartments) and Siyal (standalone, twin and townhouse villas)." },
    { q: "What are the starting prices?", a: `Chalets start from EGP ${SITE.chaletsFrom} million for a one-bedroom unit, and villas from EGP ${SITE.villasFrom} million for a townhouse. Prices are indicative and vary by unit, view and floor at the time of booking.` },
    { q: "What is a floating chalet in Ledge Valley?", a: "Ground-floor units sit on the edge of swimmable lagoons, each with a private timber deck that extends over the water, so you step straight from your home into the lagoon." },
    { q: "Who is the developer?", a: "Orascom Development — developer of El Gouna, Taba Heights and Makadi Heights — with a masterplan by EDSA and Ledge Valley designed by Die Stadt and Innovation Design Studio." },
    { q: "Can I book a site visit or get the full brochure?", a: "Yes. Leave your details or message us on WhatsApp and we'll send the brochure and available units and arrange a visit." },
  ],
  contact: {
    title: "Book before the first lagoon rows sell out",
    lead: "Front-row lagoon units are limited in every phase. Leave your number and we'll send what's available now, with prices and floor plans.",
    payment: "Instalment plans over several years",
    paymentNote: "Contact us for the payment plan available for each phase and unit.",
    formTitle: "Request prices & brochure",
    formSub: "We'll contact you on the number you provide.",
    wa: "WhatsApp",
  },
  form: {
    name: "Full name",
    phone: "Mobile / WhatsApp number",
    phase: "Phase of interest",
    undecided: "Not decided yet",
    submit: "Send me prices & brochure",
    sending: "Sending…",
    errName: "Enter your name (at least 2 characters).",
    errPhone: "Enter a valid mobile number of 10–15 digits, e.g. 01xxxxxxxxx or +9665xxxxxxxx.",
    errNet: "Your request wasn't sent because of a connection problem. Try again or message us on WhatsApp.",
    consent: "By submitting, you agree to be contacted about this project under our",
    privacy: "privacy policy",
  },
  popup: { title: "Makadi Heights price list", sub: "Prices and available units in Ledge Valley, Aden Parks and Siyal — on WhatsApp.", close: "Close" },
  mobileForm: { title: "Get the price list", sub: "Brochure and available units across all three phases, on WhatsApp." },
  bar: { call: "Call", wa: "WhatsApp", prices: "Prices" },
  cookie: { text: "We use cookies to measure ad performance and improve this page.", details: "Details", ok: "Accept", close: "Close" },
  footer: {
    title: "Makadi Heights — Hurghada",
    sub: "Ledge Valley, Aden Parks, Siyal",
    phone: "Phone & WhatsApp:",
    email: "Email:",
    disclosureLabel: "Disclosure:",
    disclosure: `This page is operated by ${SITE.brand}, an independent real estate consultant, and is not the official website of Orascom Development. Project names, trademarks and images belong to their owners and are used for identification only.`,
    pricesLabel: "Indicative prices:",
    prices: "All prices and areas shown are indicative and subject to change without notice; the final price is set by the developer at booking based on unit, floor and view. Images are architectural renders for illustration.",
    privacy: "Privacy policy & disclaimer",
  },
  privacy: {
    title: "Privacy policy & disclaimer",
    blocks: [
      { h: "", p: `This page is operated by ${SITE.brand}, an independent real estate consultant. It is not the official website of Orascom Development; all trademarks and project names belong to their owners.` },
      { h: "Data we collect", p: "We collect your name, phone number and phase of interest when you submit the form, and use them only to contact you about units, prices and visits. We do not sell your data; we may share it with the developer only to complete a booking, with your consent." },
      { h: "Cookies & advertising", p: "We use cookies and Google Ads tools to measure ad performance and enquiries. You can disable them in your browser settings." },
      { h: "Prices & specifications", p: "Prices shown are indicative and may change without notice depending on unit, floor, view and developer policy at booking. Images and plans are for illustration; areas are approximate and subject to the final contract." },
      { h: "Data deletion", p: `To request deletion of your data, email ${SITE.email} or call ${SITE.phone}.` },
    ],
    close: "Close",
  },
  thankYou: {
    metaTitle: "Request received | Makadi Heights",
    title: "Request received",
    text: "We'll contact you with Makadi Heights details and prices. If you'd like to start now, message us directly.",
    wa: "Continue on WhatsApp",
    back: "Back to home",
  },
  waDefault: "Hello, I'd like details and prices for Makadi Heights by Orascom",
  pins: { siyal: "Siyal", "aden-parks": "Aden Parks", "ledge-valley": "Ledge Valley" },
  sqm: sqm("en"),
  lvBuildings: lvBuildings("en"),
  mix: MIX.map((m) => ({ type: m.key.en, share: m.share, avg: m.avg })),
};

export const CONTENT: Record<Lang, Content> = { ar, en };
export const getT = (l: Lang) => CONTENT[l];
